### ISSUE TITLE
Unable to open "Options" page

### ISSUE THREAD

**Issue by clau-bucur** [custom-components/remote_homeassistant#100]
I've used v3.1 and now switched to "master" and in both cases the "Options" dialog cannot be opened, it just hungs here:
![image](https://user-images.githubusercontent.com/47672949/104022058-6c775100-51c8-11eb-82d6-d538fd54bf72.png)

HA restart does not help. Also the logs do not show anything.
I've enabled "debug" log level for `remote_homeassistant ` but nothing is shown there.

**Comment by danmed** [comment]
I had this, and it's because i had it manually installed previously.. so i uninstalled it, then i deleted the folder frrom custom components and then reinstalled it from HACS.

I still have the issue where it still shows it as available to install from HACS, but i can get in the menu now.

**Comment by bakboord4** [comment]
Manually installed V3.1 Tried to update "options", the same message occurred as shown above (Please wait ...).
Previous version, manually installed, worked flawlessly.
Meanwhile I will apply a snapshot recovery to restore a working remote.

Log showed:

Logger: aiohttp.server
Source: custom_components/remote_homeassistant/config_flow.py:191 
First occurred: 17:30:00 (2 occurrences) 
Last logged: 17:32:02

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 210, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 69, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 119, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1071, in async_create_flow
    return cast(OptionsFlow, HANDLERS[entry.domain].async_get_options_flow(entry))
  File "/config/custom_components/remote_homeassistant/config_flow.py", line 94, in async_get_options_flow
    return OptionsFlowHandler(config_entry)
  File "/config/custom_components/remote_homeassistant/config_flow.py", line 191, in __init__
    self.remote = self.hass.data[DOMAIN][self.config_entry.entry_id][
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by postlund** [comment]
Hmm, strange. Maybe `hass` has not been properly bound yet. Please try with `master` first, then I can make an attempt to fix it.

**Comment by bakboord4** [comment]
@postlund.
1. small correction. Previous version was installed via HACS. (instead of manually)
2. what do you mean with 'trying with master'?  Installation as an integration of HACS? Or something else?
3. I will try to install agin thru HACS and will inform you here the outcome.
thank you for your reply

**Comment by onlinepilot** [comment]
Same issue to me.
Installed integration via HACS in master version.
I´d tried to reinstall HACS (uninstall/install), I´d done a reset of HA. Because of no success, I reinstalled the HA completely.

Log:
Logger: aiohttp.server
Source: custom_components/remote_homeassistant/config_flow.py:191
First occurred: 17:40:29 (1 occurrences)
Last logged: 17:40:29

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 210, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 69, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 119, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1071, in async_create_flow
    return cast(OptionsFlow, HANDLERS[entry.domain].async_get_options_flow(entry))
  File "/config/custom_components/remote_homeassistant/config_flow.py", line 94, in async_get_options_flow
    return OptionsFlowHandler(config_entry)
  File "/config/custom_components/remote_homeassistant/config_flow.py", line 191, in __init__
    self.remote = self.hass.data[DOMAIN][self.config_entry.entry_id][
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by bakboord4** [comment]
@postlund.
HACS from 1.9 to 1.10 updated and remote home assistant (RH) as master successfully installed.
Three remarks.
1. Although installed, the new repository of RH message still appears (is already reported as issue)
2. May I suggest to document the installation from a migration point of view. Most likely RH is already installed and working. What has to done to migrate a beautiful working HA-integration to the new version.
3. To my opinion the installation documentation should reflect a choice.  (point 2: Add remote_homeassistant: to your HA configuration.) Either, you can maintain the current working situation by not updating the HA configuration. Only you cannot update your RH configuration via 'options' in the HA integration. 
Or delete the line with 'remote_homeassistant:' from your HA configuration and specify your RH configuration thru 'options' in the HA integration.

**Comment by postlund** [comment]
Please try #113, it should fix this.
