### ISSUE TITLE
I can't add entities from the instance HA.

### ISSUE THREAD

**Issue by JayChun** [custom-components/remote_homeassistant#111]
Thank you, This is really good component, I just found this today.
I have multiple HA - Main one is on Pi4B and other one is on Pi3B with Rasbian & HA supervised.

I installed the component from HACS. And the main HA discovered an Integration well as below.
![image](https://user-images.githubusercontent.com/71179304/108709735-7675c900-7556-11eb-9149-14fa3646dd81.png)

I tried to add entities from sub HA, but I can't get it.

Step 1 - set a prefix
![image](https://user-images.githubusercontent.com/71179304/108709893-ac1ab200-7556-11eb-8b94-bf61f3058cd8.png)

Step 2 - Selected domain and entities what i want to add
![image](https://user-images.githubusercontent.com/71179304/108709981-c2c10900-7556-11eb-9f95-5efe48ad6ffc.png)

Step 3 - I left the fields  by blank
![image](https://user-images.githubusercontent.com/71179304/108710162-06b40e00-7557-11eb-9928-0dfce93ff93a.png)

Step 4 - Added 2 kinds of event which I confirm Wiki 
![image](https://user-images.githubusercontent.com/71179304/108710134-fa2fb580-7556-11eb-8165-ab4cfc714511.png)

And then, nothing changed in Integration of Remote HA.
Did I make any mistakes?

Additionally, I tried to set it up in Configuration.yaml as below. but also nothing change.
`remote_homeassistant:
  instances:
  - host: 192.168.0.58
    port: 8123
    secure: true
    verify_ssl: false
    access_token: ----------------------
    entity_prefix: "PI485_"
    include:
      entities:
      - light.kocom_light_00_0
      - light.kocom_light_00_1
      - light.kocom_light_00_2
      - light.kocom_light_00_3
      - light.kocom_light_00_4
      - climate.kocom_thermostat_00
      - climate.kocom_thermostat_01
      - climate.kocom_thermostat_02
      - climate.kocom_thermostat_03
      - switch.kocom_elevator
    subscribe_events:
    - state_changed
    - service_registered`

**Comment by JayChun** [comment]
I found the error log as below.

`failed to connect
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.58', 8123)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/remote_homeassistant/__init__.py", line 371, in _async_instance_get_info
    return await async_get_discovery_info(
  File "/config/custom_components/remote_homeassistant/rest_api.py", line 46, in async_get_discovery_info
    async with session.get(url, headers=headers) as resp:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.58:8123 ssl:default [Connect call failed ('192.168.0.58', 8123)]`

**Comment by JayChun** [comment]
I tried to fix it by many ways, but It is still nothing changed.
Even so, I checked Master HA log have show normal status I think. But I can't find any integration in Integration of master HA. 

My conditions,
- Master HA : Raspi4B, SSD, Rasbian, HA Supervised, wired LAN, Core version is core-2021.2.3, Supervisor version is supervisor-2021.02.11, and installed SSL (Ngnix)
- Slave HA : Raspi3B+, SD Card and same with Master HA conditions but not installed SSL

I wrote an error log yesterday as above. The error was from SSL configuration in YAML. and it is never shown after changing configuration - "verify_ssl:" to false or deleting.

Error Log Status of Master HA
- Configuration > Log : there is no error about Remote_ha
- Supervisor > Log > Supervisor : no error
- Supervisor > Log > Core : Please see below

> 2021-02-25 10:05:09 DEBUG (MainThread) [custom_components.remote_homeassistant] received: {'id': 1, 'type': 'event', 'event': {'event_type': 'state_changed', 'data': {'entity_id': 'light.kocom_light_00_1', 'old_state': {'entity_id': 'light.kocom_light_00_1', 'state': 'on', 'attributes': {'unique_id': 'light_00_1', 'device_room': '00', 'device_type': 'light', 'friendly_name': 'kocom_light_00_1', 'supported_features': 0}, 'last_changed': '2021-02-25T01:05:00.768966+00:00', 'last_updated': '2021-02-25T01:05:00.768966+00:00', 'context': {'id': '1340108e520653371bf26c8cb19b94b3', 'parent_id': None, 'user_id': 'cd09926aa1f44a8f9a8d5b31fde8ac15'}}, 'new_state': {'entity_id': 'light.kocom_light_00_1', 'state': 'off', 'attributes': {'unique_id': 'light_00_1', 'device_room': '00', 'device_type': 'light', 'friendly_name': 'kocom_light_00_1', 'supported_features': 0}, 'last_changed': '2021-02-25T01:05:09.767390+00:00', 'last_updated': '2021-02-25T01:05:09.767390+00:00', 'context': {'id': '53677e175376fa31332ecd2b532b723d', 'parent_id': None, 'user_id': 'cd09926aa1f44a8f9a8d5b31fde8ac15'}}}, 'origin': 'LOCAL', 'time_fired': '2021-02-25T01:05:09.767390+00:00', 'context': {'id': '53677e175376fa31332ecd2b532b723d', 'parent_id': None, 'user_id': 'cd09926aa1f44a8f9a8d5b31fde8ac15'}}}
2021-02-25 10:05:09 DEBUG (MainThread) [custom_components.remote_homeassistant] received: {'id': 1, 'type': 'event', 'event': {'event_type': 'state_changed', 'data': {'entity_id': 'light.kocom_light_00_0', 'old_state': {'entity_id': 'light.kocom_light_00_0', 'state': 'on', 'attributes': {'unique_id': 'light_00_0', 'device_room': '00', 'device_type': 'light', 'friendly_name': 'kocom_light_00_0', 'supported_features': 0}, 'last_changed': '2021-02-25T01:05:00.769465+00:00', 'last_updated': '2021-02-25T01:05:00.769465+00:00', 'context': {'id': 'edd5aa64c80cb32364987633e306afb0', 'parent_id': None, 'user_id': None}}, 'new_state': {'entity_id': 'light.kocom_light_00_0', 'state': 'off', 'attributes': {'unique_id': 'light_00_0', 'device_room': '00', 'device_type': 'light', 'friendly_name': 'kocom_light_00_0', 'supported_features': 0}, 'last_changed': '2021-02-25T01:05:09.767884+00:00', 'last_updated': '2021-02-25T01:05:09.767884+00:00', 'context': {'id': 'f2acff0b7e90f6d7fa468e875d320c42', 'parent_id': None, 'user_id': None}}}, 'origin': 'LOCAL', 'time_fired': '2021-02-25T01:05:09.767884+00:00', 'context': {'id': 'f2acff0b7e90f6d7fa468e875d320c42', 'parent_id': None, 'user_id': None}}}

This is the log when I toggled button on of slave HA.
I think the Remote_HA connected well between Master ans Slave.

I think the problem is
1) HA can't discover(show) any integrations or devices of Slave HA on Integrations page of Master HA.
2) When I checked the log, it is shown all state of integrations and devices of Slave HA, even it didn't configure integrations of "Include: Domains or Entities" in YAML. 

Anyone who can let me know what should I do?

**Comment by postlund** [comment]
You will not see anything under Integrations, areas, device triggers, etc. on the main instance that is available on the remote instance. Only entities themselves are mirrored. So you should check if the entities are available. By default, everything is mirrored if no filter is applied. You should also make sure that you run the latest release as there have been some bug fixes.

**Comment by JayChun** [comment]
> You will not see anything under Integrations, areas, device triggers, etc. on the main instance that is available on the remote instance. Only entities themselves are mirrored. So you should check if the entities are available. By default, everything is mirrored if no filter is applied. You should also make sure that you run the latest release as there have been some bug fixes.

Thanks a lot! Amazing component!
I misunderstood that Configuration will discover them like this #107 
All entities are now available in master HA. and It is really stable.
