### ISSUE TITLE
Heart beat error in log

### ISSUE THREAD

**Issue by dodg3r** [custom-components/remote_homeassistant#116]
Hi.
After latest relase i get this in log when i restart hass.

```
Traceback (most recent call last):
File "/config/custom_components/remote_homeassistant/__init__.py", line 577, in _recv
await callback(message)
File "/config/custom_components/remote_homeassistant/proxy_services.py", line 58, in _async_got_services
for service in self.entry.options[CONF_SERVICES]:
KeyError: 'services'
2021-03-05 11:46:41 ERROR (MainThread) [homeassistant] Error doing job: Task was destroyed but it is pending!
2021-03-05 11:47:04 ERROR (MainThread) [custom_components.remote_homeassistant] heartbeat failed
```

Everything seems to work fine.

**Comment by postlund** [comment]
This will be fixed by #113.

**Comment by postlund** [comment]
Any luck with the latest release?

**Comment by dodg3r** [comment]
Hi.

It works great,, there is no errors in log know :)

Thanks :)

**Comment by postlund** [comment]
👍
