### ISSUE TITLE
I cannot link instances after the last update. 

### ISSUE THREAD

**Issue by Stinocon** [custom-components/remote_homeassistant#137]
Hi there!
I use this addons to be able to control some entities of my parents' house from my instance. 
There is a VPN between the two houses and the two Home Assistants talk to each other quietly. 

After issues with the last Home Assistant update I waited for today's fix and proceeded as follows:

1) Removing Remote Home Assistant from both installations.
2) Removing the old token from the secondary (slave - my parents) instance
3) Verify that there were no indications about addon in the configuration.yaml (for both instances) file and reboot.
4) Install the plugin and restart both instances
5) Insertion of 

```
remote_homeassistant:
  instances:
 
``` 
In secondary instance in configuration.yaml. and restart

Now the point is that when I try to configure Remote Home Assistant on my instance, the master one, whatever I try to enter tells me that the credentials are not correct.

https://x.x.x.x
port: 443
secure: checked
verify ssl: unchecked
token: ************

Where am I wrong?

Thanks!

**Comment by Stinocon** [comment]
Apparently whatever I try doesn't work.
I also temporarily disabled the ban_ip from configuration.yaml on the slave host to prevent it from getting in my way.

I've tried entering the hostname in the configuration on the master instance

https://x.x.x.x
https://x.x.x.x:443
x.x.x.x
x.x.x.x:443

I tried to leave the default port (8123) although home assistant is configured to respond on 443. (so for example I used https://x.x.x.x:443 in the hostname but the port then specified was 8123)
I tried not to check the secure box even though the server is in https and has a valid Let's Encrypt certificate.
I tried to regenerate the token.

In the logs of my master instance I have only this exception:

```
Traceback (most recent call last):
  File "/config/custom_components/remote_homeassistant/config_flow.py", line 78, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/remote_homeassistant/config_flow.py", line 43, in validate_input
    info = await async_get_discovery_info(
  File "/config/custom_components/remote_homeassistant/rest_api.py", line 47, in async_get_discovery_info
    async with session.get(url, headers=headers) as resp:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```
