### ISSUE TITLE
What's causing this Log errors

### ISSUE THREAD

**Issue by andzie82** [custom-components/remote_homeassistant#158]
Logs,
2022-01-11 00:35:51 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/remote_homeassistant/__init__.py", line 573, in _recv
    callback(message)
  File "/config/custom_components/remote_homeassistant/__init__.py", line 729, in got_states
    state_changed(entity_id, state, attributes)
  File "/config/custom_components/remote_homeassistant/__init__.py", line 683, in state_changed
    self._hass.states.async_set(entity_id, state, attr)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1222, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 906, in __init__
    raise InvalidEntityFormatError(
homeassistant.exceptions.InvalidEntityFormatError: Invalid entity id encountered: sun.sun. Format should be <domain>.<object_id>

**Comment by andzie82** [comment]
It was because i used two underscores in the prefix.
