### ISSUE TITLE
 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by longunmin** [custom-components/remote_homeassistant#168]
I am getting the following error when I try to setup the remote node:

```
Logger: aiohttp.server
Source: data_entry_flow.py:333
First occurred: 4:03:13 PM (1 occurrences)
Last logged: 4:03:13 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 192, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 197, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 224, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 333, in _async_handle_step
    if result["type"] not in (
TypeError: 'NoneType' object is not subscriptable
```

Using a Raspberry Pi B with Home Assistant Container on 2021.11.3 and Remote Home Assistant 3.6

**Comment by Bisket25** [comment]
This is the main issue I have been dealing with for the past 2 days. 

I’m getting this on the remote hub. 

I have mine installed through HACS. 

Running on a clean HA installation, Pi 3B plugged into Ethernet. 

Installed, added as integration, then hit configure. I’m getting this exact error. 

Master installation can connect to node but get an error or node needs remote home-assistant installed

**Comment by lukas-hetzenecker** [comment]
probably fixed in the latest release
