### ISSUE TITLE
Remote Home Assistant in Remote Node - ‘NoneType’ object is not subscriptable

### ISSUE THREAD

**Issue by gdcomunale** [custom-components/remote_homeassistant#188]
I'm using HA on a Pi4 with docker and when trying to configure remote home assistant app in "Setup as Remote Node" mode, the remote instance is correctly created but when trying to configure I get this message "Error Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble". Checking the log the error comes from here:

2022-08-12 18:26:39 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 199, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 204, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 231, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 339, in _async_handle_step
    if result["type"] not in (
TypeError: 'NoneType' object is not subscriptable

Remote home assistant app manifet.json file reports   "version": "3.6"

Home Assistant version is 2022.2.9

How can be fixed.

Thanks a lot
GD.

**Comment by lordpengwin** [comment]
i have the same problem as well, looks like it is common but there is no solution

**Comment by gdcomunale** [comment]
It's a pity none is after this bug. I tried to fix myself but not easy.D.
-------- Messaggio originale --------Da: Stephen Martin ***@***.***> Data: 17/11/22  20:33  (GMT+01:00) A: custom-components/remote_homeassistant ***@***.***> Cc: gdcomunale ***@***.***>, Author ***@***.***> Oggetto: Re: [custom-components/remote_homeassistant] Remote Home Assistant in Remote Node - ‘NoneType’ object is not subscriptable (Issue #188) 
i have the same problem as well, looks like it is common but there is no solution

**Comment by lordpengwin** [comment]
I was able to get it to work by manually installing 3.6 (not sure if its needed) setting the following lines in the remote node's configuration.yaml
```
remote_homeassistant:
  instances:
``
and restarting HA. I still get the error trying when clicking on configuration in Settings->Devices & Services->Remote Instance but there is nothing to configure there anyway. I could now discover my remote node from my local one by giving its IP address and disabling SSL.
I then took the next step and installed NginX on the remote node and set it up for SSL. Afterward, i reconfigured my local node to use the remote nodes DNS name, port 443 and enabled the SSL options. 
It all seems to work so, i'm happy.

**Comment by gdcomunale** [comment]
Hello Martin,
thank for sharing this with me. I'm in a biz trip these days, when back home I'll test it out.

D

**Comment by lukas-hetzenecker** [comment]
Should be fixed with the latest release

**Comment by gdcomunale** [comment]
Works for me. Thank a lot Lukas.
