### ISSUE TITLE
Remote Homeassistant not connecting since Update

### ISSUE THREAD

**Issue by mangp** [custom-components/remote_homeassistant#195]
Hi!
I had updated my home assistant instances to 2022.09.07 yesterday and suddenly the remote homeassistant integration isn´t connecting anymore.
On state i can see "Reconnecting" but no connection will be established.

In Logs i can seee only this:
[022-09-29 20:36:11.680 ERROR (MainThread) [custom_components.remote_homeassistant.config_flow] import of "HOSTNAME OF MY REMOTE HOMEASSISTANT" failed
Traceback (most recent call last):
File "/config/custom_components/remote_homeassistant/config_flow.py", line 165, in async_step_import
info = await validate_input(self.hass, user_input)
File "/config/custom_components/remote_homeassistant/config_flow.py", line 66, in validate_input
info = await async_get_discovery_info(
File "/config/custom_components/remote_homeassistant/rest_api.py", line 52, in async_get_discovery_info
raise ApiProblem()
custom_components.remote_homeassistant.rest_api.ApiProblem](url)

Does anybody have an idea?
Thank you in advance!

**Comment by mangp** [comment]
Hi
Nobody have an idea?

**Comment by hugalafutro** [comment]
I know "it works here" is not much help, but for what it's worth I run in docker HA 2022.10.1 and use ip not hostname and it works.

**Comment by mangp** [comment]
Hi
Thank you for your feedback - i hve tried to use ip instead of hostname but it‘s still not connecting. I use also 2022.10.1
