### ISSUE TITLE
Error on Remote Configuration button

### ISSUE THREAD

**Issue by lucacamarda** [custom-components/remote_homeassistant#202]
when i click the Configuration button in the Remote istance version 3.7 with all update homeassistant, i recieve error internal server 500.
thanks

Logger: aiohttp.server
Source: data_entry_flow.py:380
First occurred: 10:23:00 (1 occurrences)
Last logged: 10:23:00

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 218, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 225, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 380, in _async_handle_step
    if not isinstance(result["type"], FlowResultType):
TypeError: 'NoneType' object is not subscriptable

**Comment by hpirila** [comment]
Same here. RPi 3 and same error on Remote node. Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble.

Downgraded to 3.5 and still same. 

Home Assistant 2022.11.5 
Supervisor 2022.11.2 
Operating System 9.3 
Frontend 20221108.0 - latest

**Comment by lucacamarda** [comment]
i try with VM, RB3+, and docker, but not resolve. the remtoe istance when i click on configure rest 500 Internal Server Error Server got itself in trouble

**Comment by petez69** [comment]
Just had the same issue myself....Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

**Comment by ivdimitro** [comment]
I am having the same issue with 2022.12 (docker installation) and remote home assistant 3.6 and 3.7
```
2022-12-09 10:48:50.625 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 71, in _async_start
    await gather_with_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency
    return await gather(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task
    return await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 226, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 253, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/remote_homeassistant/config_flow.py", line 117, in async_step_zeroconf
    properties = info["properties"]
TypeError: 'ZeroconfServiceInfo' object is not subscriptable
```
The 3.5 is starting but the setup window is missing the labels to the input boxes and I can't configure the addon :)

**Comment by petez69** [comment]
Is this ever going to get looked at or is this a DEAD Integration ?  The error remains and we cannot configure our instancez

**Comment by ctml91** [comment]
@lukas-hetzenecker any hints or ideas of possible workarounds?

**Comment by lukas-hetzenecker** [comment]
thanks to all of you for the reports, I'll be looking into this

**Comment by petez69** [comment]
Thanks Lucas, so the message was advisory only and no impact to
functionality ?

Kind Regards..Peter
