### ISSUE TITLE
Error on my remote HomeAssistant: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by niklasbaranski** [custom-components/remote_homeassistant#206]
I followed the documentation and performed the individual steps. The setup of the local Homeassistant worked quite well.
Then I tried to add a remote node on my second Homeassistant. I get the following DEBUG error:

```
2022-12-31 11:02:20.053 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration remote_homeassistant which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-12-31 11:02:20.056 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-12-31 11:02:22.638 WARNING (MainThread) [homeassistant.components.ssdp] Could not set up UPnP/SSDP server, as a presentation URL could not be determined; Please configure your internal URL in the Home Assistant general configuration
2022-12-31 11:02:45.840 ERROR (MainThread) [aiohttp.server] Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1191, in _sendfile_fallback
    read = await self.run_in_executor(None, file.readinto, view)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 514, in start
    resp, reset = await task
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 460, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 613, in finish_response
    await prepare_meth(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_fileresponse.py", line 286, in prepare
    return await self._sendfile(request, fobj, offset, count)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_fileresponse.py", line 99, in _sendfile
    await loop.sendfile(transport, fobj, offset, count)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1170, in sendfile
    return await self._sendfile_fallback(transport, file,
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1200, in _sendfile_fallback
    await proto.restore()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 268, in restore
    self._transport.resume_reading()
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 343, in resume_reading
    self._ssl_protocol._transport.resume_reading()
AttributeError: 'NoneType' object has no attribute 'resume_reading'
2022-12-31 11:02:50.929 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 218, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 226, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 253, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 381, in _async_handle_step
    if not isinstance(result["type"], FlowResultType):
TypeError: 'NoneType' object is not subscriptable
2022-12-31 11:02:57.073 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 218, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 226, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 253, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 381, in _async_handle_step
    if not isinstance(result["type"], FlowResultType):
TypeError: 'NoneType' object is not subscriptable
```

**Comment by christophgasser** [comment]
Me too. I also got a "500 internal server error; server got itself in trouble".
Completely fresh HA setup on a Pi4. That one shoud work as slave / remote client.

**Comment by keecy** [comment]
Hi Everyone, 
Happy new Year!

I am facing the same issue in the remote instance,
Error: Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

**Comment by jpduyx** [comment]
Same error here  home-assistant operatingsystem nearly fresh

Error: Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

**Comment by crnah2o** [comment]
same here on "slave", and it's been working for quite some time up till now. the "master" doesn't exhibit similar symptoms as far as I can tell. all ha instances on latest updates.

**Comment by ctml91** [comment]
Configuring this for the first time today and I seem to have this issue too. The filters don't properly popular either when connecting the remote instance via main using the GUI, so i cannot set the domains, entities, etc to import.

**Comment by lukas-hetzenecker** [comment]
thanks to all of you for the reports, I'll be looking into this

**Comment by alosd** [comment]
same issue
...
TypeError: 'NoneType' object is not subscriptable
...

**Comment by franksteiner88** [comment]
The same problem.

**Comment by lukas-hetzenecker** [comment]
This should be fixed with the latest 3.8 release.
I tested it with Home Assistant 2023.1.0, and can no longer trigger any "500 Internal Server Error" messages.
If you still encounter any, please let me know how to reproduce them and  re-open this issue.

**Comment by vahaldor** [comment]
I have one working remote instance on the local network and just wanted to add another one. Adding new configuration opens this error message on the master instance, on which one remote (master) instance is already working.

**Comment by vahaldor** [comment]
> I have one working remote instance on the local network and just wanted to add another one. Adding new configuration opens this error message on the master instance, on which one remote (master) instance is already working.
> 
> Error Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

SOLVED: Redownload the remote homeassistant plugin in HACS/integrations (three dots top-right corner)
