### ISSUE TITLE
new error   with latest update.... await self._loop.create_connection(*args, **kwargs +2 Other Errors 

### ISSUE THREAD

**Issue by comet424** [custom-components/remote_homeassistant#251]
so the latest fix   fixed... the remote connection error i was getting that i posted... but now it has a new connection error..
i keep getting i can access HA 192.168.1.12  no problem  but the Logs keeps reporting an error  and my 2 remote HA connected to my main are all up to date with the latest remote home assistance connection  plugin

```
This error originated from a custom integration.

Logger: custom_components.remote_homeassistant
Source: custom_components/remote_homeassistant/rest_api.py:47
Integration: Remote Home-Assistant (documentation, issues)
First occurred: 4:57:12 PM (2 occurrences)
Last logged: 4:59:31 PM

failed to connect
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('192.168.1.12', 8123)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/remote_homeassistant/__init__.py", line 373, in _async_instance_get_info
    return await async_get_discovery_info(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/remote_homeassistant/rest_api.py", line 47, in async_get_discovery_info
    async with session.get(url, headers=headers) as resp:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.12:8123 ssl:default [Connect call failed ('192.168.1.12', 8123)]

```

**Comment by comet424** [comment]
second Remote Home assistant error is 

```
Logger: custom_components.remote_homeassistant
Source: custom_components/remote_homeassistant/rest_api.py:49
Integration: Remote Home-Assistant ([documentation](https://github.com/custom-components/remote_homeassistant), [issues](https://github.com/custom-components/remote_homeassistant/issues))
First occurred: 5:28:49 PM (1 occurrences)
Last logged: 5:28:49 PM

failed to fetch instance info
Traceback (most recent call last):
  File "/config/custom_components/remote_homeassistant/__init__.py", line 373, in _async_instance_get_info
    return await async_get_discovery_info(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/remote_homeassistant/rest_api.py", line 49, in async_get_discovery_info
    raise EndpointMissing()
custom_components.remote_homeassistant.rest_api.EndpointMissing

```

**Comment by comet424** [comment]
Third Error i got now  is 

```
This error originated from a custom integration.

Logger: custom_components.remote_homeassistant
Source: custom_components/remote_homeassistant/__init__.py:460
Integration: Remote Home-Assistant (documentation, issues)
First occurred: 7:25:06 PM (1 occurrences)
Last logged: 7:25:06 PM

heartbeat failed
```


whatever a heart beat is

**Comment by lukas-hetzenecker** [comment]
custom_components.remote_homeassistant.rest_api.EndpointMissing is caused by a missing installation of remote_homeassistant on the remote node. Please install the component also on that one, as instructed in the documentation.
