### ISSUE TITLE
Cannot start with 2024.12.b1

### ISSUE THREAD

**Issue by Bluhme1** [custom-components/remote_homeassistant#328]
See log

Denne fejl stammer fra en brugerdefineret integration.

Logger: homeassistant
Kilde: custom_components/remote_homeassistant/__init__.py:455
integration: Remote Home-Assistant (dokumentation, problemer)
Første forekomst: 13.47.58 (1 forekomster)
Senest logget: 13.47.58

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/remote_homeassistant/__init__.py", line 265, in setup_components_and_platforms
    await remote.async_connect()
  File "/config/custom_components/remote_homeassistant/__init__.py", line 455, in async_connect
    self._connection = await session.ws_connect(url, max_msg_size = self._max_msg_size)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 1107, in _ws_connect
    conn_proto.set_parser(WebSocketReader(reader, max_msg_size), reader)
                          ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
TypeError: Argument 'max_msg_size' has incorrect type (expected int, got NoneType)

**Comment by alsFC** [comment]
Still broken in 2024.12.0

**Comment by SinclairKS** [comment]
Not a programmer, but forcing the max_msg_size value to 16777216 (default max from the const.py file) allows the integration to return to normal operation (as far as I've seen so far). Didn't trace the issue any further (and I just tinker) but best as I can see the value being read at the top of the __init__.py file seems to be coming up empty. Probably a simple actual fix.

Line 455 in __init__.py:                 self._connection = await session.ws_connect(url, max_msg_size = 16777216)

**Comment by jaym25** [comment]
Update to version 4.4
