### ISSUE TITLE
Error during setup of component remote_homeassistant InvalidEntityFormatError

### ISSUE THREAD

**Issue by HugoLet** [custom-components/remote_homeassistant#63]
Hi there,
`
Error during setup of component remote_homeassistant
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/remote_homeassistant/__init__.py", line 109, in async_setup
    connection = RemoteConnection(hass, instance)
  File "/config/custom_components/remote_homeassistant/__init__.py", line 187, in __init__
    self.set_connection_state(STATE_CONNECTING)
  File "/config/custom_components/remote_homeassistant/__init__.py", line 201, in set_connection_state
    self._hass.states.async_set(self._connection_state_entity, state, self._instance_attrs)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1183, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 865, in __init__
    raise InvalidEntityFormatError(
homeassistant.exceptions.InvalidEntityFormatError: Invalid entity id encountered: sensor.remote_connection_https://domaine_duckdns_org_443. Format should be <domain>.<object_id>`

my config yaml :

remote_homeassistant:
  instances:
  - host: https://domaine.duckdns.org
    port: 443
    secure: true
    verify_ssl: false
    access_token: eyJ0eXA....
    #entity_prefix: "lpn_"

Any idea to fix this?
Thanks!

**Comment by postlund** [comment]
Skip `https://` in `host` (it's derived from `secure: true`).

**Comment by HugoLet** [comment]
Same result with or without https. I disabel the configuration from my yaml and add it directly into integration and work fine!
But we are not abble to define an entity_prefix into it.

I gona try to put this into the yaml.

**Comment by postlund** [comment]
Did you make any progress on this?

**Comment by postlund** [comment]
I believe this is not actually an issue anymore. Feel free to open again if it is.
